sonar.projectKey=EnzoAnzite_Candidia
sonar.organization=enzoanzite

sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8